services:
  server:
    container_name: echo_server
    build: ./
    command: uvicorn echo.app:app --host 0.0.0.0
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    networks:
      - db
      - server
    depends_on:
      - db
    restart: always

  client:
    container_name: echo_client
    build: ./client
    stdin_open: true
    networks:
      - client

  nginx:
    container_name: echo_nginx
    image: nginx:mainline-alpine
    volumes:
      - ./echo_nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - server
      - client
    depends_on:
      - server
      - client
    restart: always

  db:
    container_name: echo_db
    image: postgres:13-alpine
    volumes:
      - ./.db/data:/db
    networks:
      - db
    environment:
      - POSTGRES_PASSWORD=www
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/db
    restart: always

networks:
  db:
    driver: bridge
  server:
    driver: bridge
  client:
    driver: bridge
