services:
  app:
    container_name: echo_app
    build: ./
    command: uvicorn echo.app:app
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app/client
    networks:
      - db
      - web
    depends_on:
      - db
    restart: always

  nginx:
    container_name: echo_nginx
    image: nginx:latest
    volumes:
      - ./echo_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/client
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
    restart: always

  db:
    container_name: echo_db
    image: postgres:latest
    volumes:
      - ./.db/data:/db
#    ports:
#      - 5432:5432
    networks:
      - db
    environment:
      - POSTGRES_PASSWORD=www
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/db
    restart: always

networks:
  db:
    driver: bridge
  web:
    driver: bridge
